/*
 * generated by Xtext 2.25.0
 */
package eu.lowcomote.keptn.sli;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SliRuntimeModule extends AbstractSliRuntimeModule {
}
