/*
 * generated by Xtext 2.25.0
 */
package eu.lowcomote.keptn.sli.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.lowcomote.keptn.sli.SliRuntimeModule;
import eu.lowcomote.keptn.sli.SliStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SliIdeSetup extends SliStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SliRuntimeModule(), new SliIdeModule()));
	}
	
}
