/*
 * generated by Xtext 2.25.0
 */
package eu.lowcomote.keptn.sli.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SliUiModule extends AbstractSliUiModule {

	public SliUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
