/*
 * generated by Xtext 2.25.0
 */
package eu.lowcomote.keptn.slo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SloUiModule extends AbstractSloUiModule {

	public SloUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
