/*
 * generated by Xtext 2.25.0
 */
package eu.lowcomote.keptn.slo.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.lowcomote.keptn.slo.SloRuntimeModule;
import eu.lowcomote.keptn.slo.SloStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SloIdeSetup extends SloStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SloRuntimeModule(), new SloIdeModule()));
	}
	
}
