/*
 * generated by Xtext 2.25.0
 */
package eu.lowcomote.keptn.slo.validation;

import org.eclipse.emf.common.util.URI;
import org.eclipse.ocl.xtext.completeocl.validation.CompleteOCLEObjectValidator;
import org.eclipse.xtext.validation.EValidatorRegistrar;

import eu.lowcomote.keptn.slo.SloPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class SloValidator extends AbstractSloValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					SloPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
	public void register(EValidatorRegistrar registrar) {
        super.register(registrar);
        SloPackage ePackage = SloPackage.eINSTANCE;
        
        
        URI basicOclURI = URI.createPlatformPluginURI("/eu.lowcomote.keptn.slo.model/sloOpt.ocl", true);	
        registrar.register(ePackage, new CompleteOCLEObjectValidator(ePackage, basicOclURI));
        
	}	

	
}
